version: '3'
services:
  web:
    image: ghcr.io/hackclub/hcb
    build:
      context: .
      dockerfile: production.Dockerfile
  jobs:
    image: ghcr.io/hackclub/hcb
    depends_on: [ web ] # Wait for web to build docker image
    command: bundle exec sidekiq
    environment:
      RAILS_MAX_THREADS: 4 # 4 threads x 3 workers = 12 threads
